### ISSUE TITLE
固件编译问题 - 如何设置固定ip/wifi-ap，或能否帮忙对目前固件开启usb gadget等功能重新make，可有偿

### ISSUE THREAD

**Issue by ywz978020607** [wu17481748/UFI-debian11#2]
您好，我参考的这篇编译流程：https://www.momoe.link/shizuku/065919.html
以及苏苏小亮亮固件编译，想问问怎么开启rndis以及设置固定ip或者设置默认wifi热点或wifi-sta，目前生成的固件刷入后无法通过rndis/wifi-ap/wifi-sta连接。
或者大佬能将您目前的固件开启一下menuconfig里gadget相关的配置再生成一版固件吗，可以有偿，微信：moyudage123

**Comment by wu17481748** [comment]
直接按这个教程rndis是开启的。

**Comment by ywz978020607** [comment]
大佬新年快乐~
我按他的教程刷上发现就直接闪红灯了，电脑看了一下设备管理器和ipconfig都无；如果直接刷您的那个固件，刷完直接就出来了，而且也会有wifi-ap出现，不走rndis也能连上。
我刚刚又试了几次都是这样，大佬有时间可否有偿给指导一下，或者出一版开启了usb所有gadget组件功能的固件

**Comment by ywz978020607** [comment]
> 直接按这个教程rndis是开启的。

感谢大佬，解决了，是之前没按照先base后debian刷法，而直接用了一个红色背景一键式刷入并替换了两个img文件导致的，后来使用base+debian(复制两个文件)，可以了，尝试了一下在固件编译时开启usb gadget，刷入后没问题了~
